version: '3'

services:
    nginx:
        container_name: labyrinth_nginx
        image: nginx:stable
        restart: unless-stopped
        tty: true
        ports:
            - "9040:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/logs:/var/log/nginx
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - labyrinth-net

    php:
        container_name: labyrinth_php
        image: labyrinth_php
        build:
            context: .
            dockerfile: .docker/php/php.Dockerfile
        restart: unless-stopped
        tty: true
        stdin_open: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        ports:
            - "9041:9041"
        volumes:
            - ./:/var/www/html
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        depends_on:
            - db
        networks:
            - labyrinth-net

    db:
        container_name: labyrinth_db
        image: mariadb:latest
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: labyrinth
            MYSQL_ROOT_PASSWORD: root
            MYSQL_TCP_PORT: 9042
        ports:
            - "9042:9042"
        volumes:
            - ./.docker/mariadb/data:/var/lib/mysql
        networks:
            - labyrinth-net

    pma:
        container_name: labyrinth_pma
        image: phpmyadmin:latest
        restart: unless-stopped
        tty: true
        environment:
            PMA_HOST: labyrinth_db
            PMA_PORT: 9042
            PMA_PASSWORD: root
        ports:
            - "9043:80"
        depends_on:
            - db
        networks:
            - labyrinth-net

networks:
    labyrinth-net:
        driver: bridge
